indent-width = 4
line-length = 99
target-version = "py39"

[lint]
select = [
    "C90", # mccabe
    "E",  # pycodestyle
    "F",  # Pyflakes + flake8
    "I",  # isort
    "UP", # pyupgrade
    "W",  # pycodestyle
]
